name: conan

on:
  pull_request:
    paths-ignore: "docs/**"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install conan
        run: pip install conan
      - name: Set conan profile
        run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Run conan build package
        run: conan create . kappa/stable -c tools.system.package_manager:mode=install