name: cpp-linter

on:
  push:
    paths-ignore: "docs/**"
  pull_request:
    paths-ignore: "docs/**"

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install conan
      - run: pip install conan
      - name: Install dependencies
      - run: mkdir build && cd build && conan install .. -s build_type=Debug --build=missing
      - name: Build
      - run: cd build && cmake build .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cmake --build . --config Debug --target KappaEngineTests